filemanager_icon:
    incbin "build/assets/filemanager_32.raw"

internetexplorer_icon:
    incbin "build/assets/internetexplorer_32.raw"

activitymanager_icon:
    incbin "build/assets/activitymanager_32.raw"

paint_icon:
    incbin "build/assets/paint_32.raw"

boot_log_screen:
    incbin "build/assets/bootupscreenlog_320x156.raw"

boot_screen:
    incbin "build/assets/bootupscreen_320x156.raw"

cursor_icon:
    incbin "build/assets/cursor_16.raw"

cursor_selected_icon:
    incbin "build/assets/cursorselected_16.raw"
